#!/usr/bin/env python3
# Generated by braise's scaffold_brainlife_app.py -- adapts compute_dwi_snr_hm_vm.py (an
# existing CLI-style script, unmodified) to brainlife's config.json
# convention: load config.json, substitute its values into the --invoke
# command template from the app manifest, and run it.
import json
import shlex
import subprocess
import sys

with open("config.json") as f:
    config = json.load(f)

command = 'python compute_dwi_snr_hm_vm.py --subject subject --dwi "{dwi}" --bval "{bvals}" --bvec "{bvecs}" --polar-angle "{polarAngle}" --eccentricity "{eccentricity}" --varea "{varea}" --varea-labels "{varea_labels}" --b0-thr "{b0_thr}" --out-dir ./work --out-csv stats/some.csv'.format(**config)
print(f"+ {command}")
result = subprocess.run(shlex.split(command))
sys.exit(result.returncode)
